export const CHANGE_TITLE = "CHANGE_TITLE";
export const CHANGE_PALETTE_BLOCK = "CHANGE_PALETTE_BLOCK";
export const CHANGE_PALETTE_INDEX = "CHANGE_PALETTE_INDEX";
export const CHANGE_COLOR = "CHANGE_COLOR";